services:
  mysql:
    image: mysql:8.0
    container_name: inventory-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    #      MYSQL_DATABASE: order_service
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
